name: necopia
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.2
  firebase_core: ^2.14.0
  flame: ^1.8.1
  flutter:
    sdk: flutter
  get: ^4.6.5
  firebase_auth: ^4.6.3
  flutter_launcher_icons: ^0.13.1
  percent_indicator: ^4.2.3
  geolocator: ^9.0.2
  http: ^1.1.0
  animated_text_kit: ^4.2.2
  audioplayers: ^5.0.0
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # firebase_auth: ^4.6.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/pawlogo.png"
  adaptive_icon_foreground: "assets/images/pawlogo.png"
  adaptive_icon_background: "assets/images/pawlogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/button/
    - assets/images/
    - assets/images/cat/
    - assets/images/item/
    - assets/images/sky/
    - assets/images/rain/
    - assets/audio/
    - assets/ad/
  fonts:
    - family: Minecraft
      fonts:
        - asset: assets/fonts/Minecraft.ttf
    - family: Inscryption
      fonts:
        - asset: assets/fonts/Inscryption.ttf
    - family: Pixelate
      fonts: 
        - asset: assets/fonts/Pixelate.ttf
